### ISSUE TITLE
Divide diagrams in pages

### ISSUE THREAD

**Issue by Razican** [Razican/FDP#5]
Currently, both precedence and Gantt diagrams are stretched to one page. They should be divided in more pages to improve readability.

**Comment by Alchemy-Meister** [comment]
Adding to much rubbish, simplify it.

**Comment by Razican** [comment]
Where?

**Comment by Alchemy-Meister** [comment]
Simplify the box layout of the network diagram, remove illegible resource names in gantt and add introduction text in both gantt and graphs.
